title: Desktop Entry Daemon Docs
description: Documentation for Desktop Entry Daemon
theme: just-the-docs

url: https://ryanabx.github.io/desktop-entry-daemon

aux_links:
  GitHub: https://github.com/ryanabx/desktop-entry-daemon
